-- Create chat_messages table for patient chatbot
CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    detection_id UUID REFERENCES detections(id) ON DELETE SET NULL,
    user_message TEXT NOT NULL,
    bot_response TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX idx_chat_messages_user_id ON chat_messages(user_id);
CREATE INDEX idx_chat_messages_detection_id ON chat_messages(detection_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at DESC);

-- Add comment to table
COMMENT ON TABLE chat_messages IS 'Stores patient chatbot conversation history';
COMMENT ON COLUMN chat_messages.user_id IS 'Patient user ID (role must be PATIENT)';
COMMENT ON COLUMN chat_messages.detection_id IS 'Optional reference to detection being discussed';
COMMENT ON COLUMN chat_messages.user_message IS 'Message sent by the patient';
COMMENT ON COLUMN chat_messages.bot_response IS 'Response generated by Mistral-7B chatbot';
