// frontend/src/components/detection/ShareDialog.tsx
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../ui/dialog';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { toast } from 'sonner';
import { Download, Mail, Copy, Check, Link as LinkIcon } from 'lucide-react';
import { reportService } from '../../services/reportService';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';

// Social platform icon components (inline SVGs — no extra dependencies)
const WhatsAppIcon = () => (
  <svg viewBox="0 0 24 24" className="h-5 w-5 fill-current" xmlns="http://www.w3.org/2000/svg">
    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
  </svg>
);

const TelegramIcon = () => (
  <svg viewBox="0 0 24 24" className="h-5 w-5 fill-current" xmlns="http://www.w3.org/2000/svg">
    <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/>
  </svg>
);

const TwitterXIcon = () => (
  <svg viewBox="0 0 24 24" className="h-5 w-5 fill-current" xmlns="http://www.w3.org/2000/svg">
    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.745l7.73-8.835L1.254 2.25H8.08l4.259 5.631zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
  </svg>
);

interface ShareDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  detectionId: string;
  detection_id: string;
}

interface SocialPlatform {
  name: string;
  icon: React.ReactNode;
  bgColor: string;
  hoverColor: string;
  textColor: string;
  getUrl: (text: string, url: string) => string;
}

const SOCIAL_PLATFORMS: SocialPlatform[] = [
  {
    name: 'WhatsApp',
    icon: <WhatsAppIcon />,
    bgColor: 'bg-[#25D366]',
    hoverColor: 'hover:bg-[#20b859]',
    textColor: 'text-white',
    getUrl: (text, url) =>
      `https://api.whatsapp.com/send?text=${encodeURIComponent(`${text}\n${url}`)}`,
  },
  {
    name: 'Telegram',
    icon: <TelegramIcon />,
    bgColor: 'bg-[#229ED9]',
    hoverColor: 'hover:bg-[#1a8cbf]',
    textColor: 'text-white',
    getUrl: (text, url) =>
      `https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text)}`,
  },
  {
    name: 'Twitter / X',
    icon: <TwitterXIcon />,
    bgColor: 'bg-[#000000]',
    hoverColor: 'hover:bg-[#1a1a1a]',
    textColor: 'text-white',
    getUrl: (text, url) =>
      `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,
  },
];

export const ShareDialog: React.FC<ShareDialogProps> = ({
  open,
  onOpenChange,
  detectionId,
  detection_id,
}) => {
  const [email, setEmail] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSharingPDF, setIsSharingPDF] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const shareUrl = window.location.href;
  const shareText = `Dental Caries Detection Report (ID: ${detection_id}) — Generated by DentAI Diagnostics.`;

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      toast.success('Link copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy link');
    }
  };

  const handleSendEmail = async () => {
    if (!email) { toast.error('Please enter an email address'); return; }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { toast.error('Invalid email format'); return; }

    setIsSending(true);
    try {
      await reportService.emailReport(detectionId, email);
      toast.success(`Report sent to ${email}`);
      setEmail('');
    } catch (e: unknown) {
      console.error(e);
      toast.error('Failed to send email');
    } finally {
      setIsSending(false);
    }
  };

  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    try {
      const blob = await reportService.downloadPDF(detectionId);
      reportService.triggerDownload(blob, `Detection_Report_${detection_id}.pdf`);
      toast.success('Report downloaded successfully');
    } catch {
      toast.error('Failed to download PDF');
    } finally {
      setIsDownloading(false);
    }
  };

  // Download PDF then share the file via the Web Share API (mobile), or open social URL (desktop)
  const handleShareViaPlatform = async (platform: SocialPlatform) => {
    setIsSharingPDF(platform.name);
    try {
      // First try to download PDF so the user has it locally
      const blob = await reportService.downloadPDF(detectionId);
      const pdfFile = new File([blob], `Detection_Report_${detection_id}.pdf`, { type: 'application/pdf' });

      // Try native Web Share API with file (works on mobile browsers)
      if (navigator.canShare && navigator.canShare({ files: [pdfFile] })) {
        await navigator.share({
          title: 'Dental Detection Report',
          text: shareText,
          files: [pdfFile],
        });
        toast.success(`PDF shared via ${platform.name}`);
      } else {
        // Fallback: save PDF locally + open social platform with the link
        reportService.triggerDownload(blob, `Detection_Report_${detection_id}.pdf`);
        toast.info('PDF saved. Opening sharing platform…');
        setTimeout(() => {
          window.open(platform.getUrl(shareText, shareUrl), '_blank', 'noopener,noreferrer');
        }, 800);
      }
    } catch (err: unknown) {
      if (err instanceof Error && err.name !== 'AbortError') {
        // User cancelled share — fall back to opening social link only
        window.open(platform.getUrl(shareText, shareUrl), '_blank', 'noopener,noreferrer');
      }
    } finally {
      setIsSharingPDF(null);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md bg-white rounded-[20px] p-0 border-none shadow-2xl gap-0 overflow-hidden">

        {/* Header */}
        <div className="p-6 pb-2 relative">
          <DialogHeader className="text-left space-y-1">
            <DialogTitle className="text-xl font-bold text-slate-800">Share Report</DialogTitle>
            <p className="text-sm text-slate-500">
              Share analysis{' '}
              <span className="font-mono text-xs bg-slate-100 px-1 py-0.5 rounded text-slate-600">
                {detection_id}
              </span>{' '}
              with colleagues or patients.
            </p>
          </DialogHeader>
        </div>

        <div className="p-6 space-y-6">

          {/* Report Link */}
          <div className="space-y-2.5">
            <Label className="text-xs font-bold text-slate-400">Report Link</Label>
            <div className="flex gap-2">
              <div className="relative flex-1 group">
                <div className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 group-hover:text-primary transition-colors">
                  <LinkIcon className="h-4 w-4" />
                </div>
                <Input
                  readOnly
                  value={shareUrl}
                  className="pl-10 h-11 bg-slate-50 border-slate-200 text-slate-600 font-medium text-sm focus-visible:ring-primary rounded-xl"
                />
              </div>
              <Button
                onClick={handleCopyLink}
                variant="outline"
                size="icon"
                className={`h-11 w-11 shrink-0 rounded-xl border-slate-200 transition-all ${
                  copied
                    ? 'bg-green-50 text-green-600 border-green-200 hover:bg-green-100 hover:text-green-700'
                    : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                }`}
              >
                {copied ? <Check className="h-5 w-5" /> : <Copy className="h-5 w-5" />}
              </Button>
            </div>
          </div>

          {/* Social Sharing */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <Label className="text-sm font-semibold text-slate-800">Share PDF via</Label>
            </div>
            <div className="grid grid-cols-3 gap-2.5">
              {SOCIAL_PLATFORMS.map((platform) => (
                <button
                  key={platform.name}
                  onClick={() => handleShareViaPlatform(platform)}
                  disabled={isSharingPDF === platform.name}
                  className={`flex flex-col items-center justify-center gap-1.5 py-3 px-2 rounded-xl font-medium text-xs transition-all active:scale-95 disabled:opacity-70 ${platform.bgColor} ${platform.hoverColor} ${platform.textColor}`}
                >
                  {isSharingPDF === platform.name ? (
                    <LoadingSpinner size="sm" />
                  ) : (
                    platform.icon
                  )}
                  <span>{platform.name}</span>
                </button>
              ))}
            </div>
            <p className="text-[11px] text-slate-400 leading-snug">
              The PDF will be downloaded to your device and the sharing platform will open with a pre-filled message.
            </p>
          </div>

          {/* Email Section */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <Mail className="h-4 w-4 text-slate-800" />
              <Label className="text-sm font-semibold text-slate-800">Send via Email</Label>
            </div>
            <div className="flex gap-2">
              <Input
                placeholder="doctor@clinic.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="h-11 bg-slate-50 border-slate-200 rounded-xl focus-visible:ring-primary"
                onKeyDown={(e) => e.key === 'Enter' && handleSendEmail()}
              />
              <Button
                onClick={handleSendEmail}
                disabled={isSending || !email}
                className="h-11 px-6 bg-primary hover:bg-primary/90 text-white rounded-xl font-medium shadow-md shadow-primary/10 transition-all"
              >
                {isSending ? <LoadingSpinner size="md" /> : 'Send'}
              </Button>
            </div>
          </div>

          {/* Download PDF */}
          <div className="pt-2">
            <Button
              variant="outline"
              onClick={handleDownloadPDF}
              disabled={isDownloading}
              className="w-full h-12 border-slate-200 text-slate-600 font-medium hover:bg-slate-50 hover:text-slate-900 rounded-xl transition-all"
            >
              {isDownloading ? (
                <>
                  <LoadingSpinner size="md" />
                  <span className="ml-2">Generating PDF...</span>
                </>
              ) : (
                <>
                  <Download className="mr-2 h-4 w-4" />
                  Save PDF
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};